name: publish package

on:
  create:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 11
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish svelte-intl2
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
